python -c "from test_prime import test_prime; test_prime(2, True)"
python -c "from test_prime import test_prime; test_prime(3, True)"
python -c "from test_prime import test_prime; test_prime(5, True)"
python -c "from test_prime import test_prime; test_prime(10, False)"
python -c "from test_prime import test_prime; test_prime(25, False)"