# Generated by Django 4.2.5 on 2023-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
